/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import LearnClip from "./scripts/LearnClip"
import LearnList from "./scripts/LearnList"
import LearnScrollbar from "./scripts/LearnScrollbar"
import LearnRunTime from "./scripts/LearnRunTime"
import LearnText from "./scripts/LearnText"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("scripts/LearnClip.js",LearnClip);
		reg("scripts/LearnList.js",LearnList);
		reg("scripts/LearnScrollbar.js",LearnScrollbar);
		reg("scripts/LearnRunTime.js",LearnRunTime);
		reg("scripts/LearnText.js",LearnText);
    }
}
GameConfig.width = 720;
GameConfig.height = 1280;
GameConfig.scaleMode ="showall";
GameConfig.screenMode = "none";
GameConfig.alignV = "middle";
GameConfig.alignH = "center";
GameConfig.startScene = "Clip.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = false;
GameConfig.exportSceneToJson = true;

GameConfig.init();
